//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportData.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExportData.UI.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Criterion.
        /// </summary>
        public static string AddCriterion {
            get {
                return ResourceManager.GetString("AddCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing DB.
        /// </summary>
        public static string BrowseDb {
            get {
                return ResourceManager.GetString("BrowseDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browsing content.
        /// </summary>
        public static string BrowsingСontentLabel {
            get {
                return ResourceManager.GetString("BrowsingСontentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close App?.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection error.
        /// </summary>
        public static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion.
        /// </summary>
        public static string Criterion {
            get {
                return ResourceManager.GetString("Criterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion Value.
        /// </summary>
        public static string CtriterionValue {
            get {
                return ResourceManager.GetString("CtriterionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No criterion selected or empty criterion value.
        /// </summary>
        public static string EmptyCriterion {
            get {
                return ResourceManager.GetString("EmptyCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty or not open.
        /// </summary>
        public static string ErrorAddingDB {
            get {
                return ResourceManager.GetString("ErrorAddingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File export.
        /// </summary>
        public static string ExportFile {
            get {
                return ResourceManager.GetString("ExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XML.
        /// </summary>
        public static string ExportXML {
            get {
                return ResourceManager.GetString("ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload error. Check if the contents of the file are correct.
        /// </summary>
        public static string FileOpenError {
            get {
                return ResourceManager.GetString("FileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering error.
        /// </summary>
        public static string FilterError {
            get {
                return ResourceManager.GetString("FilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Result.
        /// </summary>
        public static string FilterResult {
            get {
                return ResourceManager.GetString("FilterResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load DB.
        /// </summary>
        public static string LoadDB {
            get {
                return ResourceManager.GetString("LoadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload.
        /// </summary>
        public static string LoadFileMenu {
            get {
                return ResourceManager.GetString("LoadFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load to DB.
        /// </summary>
        public static string LoadToDb {
            get {
                return ResourceManager.GetString("LoadToDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion added successfully.
        /// </summary>
        public static string SuccessAddingCriterion {
            get {
                return ResourceManager.GetString("SuccessAddingCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to the database.
        /// </summary>
        public static string SuccessAddingDB {
            get {
                return ResourceManager.GetString("SuccessAddingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opened successfully!.
        /// </summary>
        public static string SuccessOpen {
            get {
                return ResourceManager.GetString("SuccessOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurName.
        /// </summary>
        public static string SurName {
            get {
                return ResourceManager.GetString("SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
